name: $(BuildID)

trigger:
  - test

pr: none

variables:
  image: dixaba/test

jobs:
  - job: big
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: 'docker login'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: login

    - task: Bash@3
      displayName: 'build.sh base'
      inputs:
        targetType: filePath
        filePath: ./build.sh
        arguments: big
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: Docker@1
      displayName: 'docker push'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: $(image)


  - job: latest
    dependsOn:
    - big
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: 'docker login'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: login

    - task: Bash@3
      displayName: 'build.sh base'
      inputs:
        targetType: filePath
        filePath: ./build.sh
        arguments: latest
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: Docker@1
      displayName: 'docker push'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: $(image)


  - job: latestx64
    dependsOn:
    - big
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: 'docker login'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: login
    
    - task: Bash@3
      displayName: 'build.sh base'
      inputs:
        targetType: filePath
        filePath: ./build.sh
        arguments: latest-x64
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: Docker@1
      displayName: 'docker push'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: $(image)


  - job: both
    dependsOn:
    - latest
    - latestx64
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: 'docker login'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: login
    
    - task: Bash@3
      displayName: 'build.sh base'
      inputs:
        targetType: filePath
        filePath: ./build.sh
        arguments: both
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: Docker@1
      displayName: 'docker push'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: $(image)